forge 'https://forgeapi.puppetlabs.com'

mod 'bashtoni/timezone'
mod 'bstopp/aem'
mod 'jfryman/selinux'
mod 'kemra102/cloudwatchlogs'
mod 'maestrodev/wget'
mod 'pcfens/rhn_register'
mod 'puppet/archive'
mod 'puppetlabs/apache'
mod 'aco-oracle_java', '2.8.0'
mod 'shinesolutions/aem_resources', :git => 'https://github.com/shinesolutions/puppet-aem-resources'
mod 'puppet-collectd', '5.3.0'
