---
version: 5
defaults:
  datadir: data
  data_hash: yaml_data

hierarchy:
  - name: OS family, name and major release
    path: "%{::os.family}/%{::os.name}-%{::os.release.major}.yaml"
    data_hash: yaml_data

  - name: OS family and name
    path: "%{::os.family}/%{::os.name}.yaml"
    data_hash: yaml_data

  - name: OS family
    path: "%{::os.family}.yaml"
    data_hash: yaml_data

  - name: Common
    path: common.yaml
    data_hash: yaml_data
